version: '3.8'

services:
  backend:
    build: ./fixtrack-backend
    ports:
      - "5000:5000"
    env_file:
      - ./fixtrack-backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./fixtrack-frontend
    ports:
      - "4173:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db



  n8n:
    image: n8nio/n8n
    ports:
      - "5679:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  mongo_data:
  n8n_data:
  